### ISSUE TITLE
byebyepasswordHelper::setPlugin() should not be called statically

### ISSUE THREAD

**Issue by 4ACC** [readybytes/ByeByePassword#14]
Hi,

I got this error if users click link in email?  

a. Click URL
b. browser displays error for only 2 seconds:
Strict Standards: Non-static method byebyepasswordHelper::setPlugin() should not be called statically, assuming $this from incompatible context in /public_html/joomla/plugins/system/byebyepassword/byebyepassword.php on line 88

c. and it redirects and is correct logged in!

What to do, thanks igo

**Comment by rbsl-rimjhim** [comment]
Hi,

Thanks for reporting this issue.

Follow these steps to fix it - 
1. Go to file : root/plugins/system/byebyepassword/helper.php
2. Find code (near line 15) -
function setPlugin()
3. Replace it with -
static function setPlugin()

Let me know if still you face any issue.

**Comment by 4ACC** [comment]
Yep,

solved the problem, Great and fast service 

Many, thanks

**Comment by rbsl-rimjhim** [comment]
Thanks.

If you like the working of this plugin then don't forget to share your words at <a target="_blank" href="http://extensions.joomla.org/extensions/extension/access-a-security/site-access/bye-bye-password">JED</a>JED :)
